/**
 * Markdown Generator
 *
 * Generates daily AI calendar markdown content
 * from summarized GitHub repositories.
 */

import fs from "fs";
import path from "path";

/**
 * Format a single repository section
 *
 * @param {Object} repo
 * @returns {string}
 */
function formatRepoSection(repo) {
  return `
### 🔹 ${repo.name}

- ⭐ **Stars:** ${repo.stars}
- 🧠 **Language:** ${repo.language || "N/A"}
- 🔗 **Repo:** ${repo.url}

**Summary (EN):**
${repo.summary_en}

**摘要（中文）：**
${repo.summary_cn}

**Why it matters:**
${repo.why_it_matters}
`.trim();
}

/**
 * Generate full markdown content
 *
 * @param {Object} options
 * @param {string} options.date - YYYY-MM-DD
 * @param {string} options.category
 * @param {Array} options.repos
 * @returns {string}
 */
export function generateMarkdown({
  date,
  category = "AI",
  repos = []
}) {
  if (!date) {
    throw new Error("generateMarkdown requires a date");
  }

  const header = `
# 📅 AI Daily Calendar — ${date}

**Category:** ${category}

> Automatically generated by GitHub Actions.
> English summaries + Chinese highlights.

---
`.trim();

  const body = repos.length
    ? repos.map(formatRepoSection).join("\n\n---\n\n")
    : "_No qualified repositories found today._";

  const footer = `
---
Generated at ${new Date().toISOString()}
`.trim();

  return `${header}\n\n${body}\n\n${footer}\n`;
}

/**
 * Save markdown file to /daily directory
 *
 * @param {string} content
 * @param {string} date - YYYY-MM-DD
 * @returns {string} filePath
 */
export function saveDailyMarkdown(content, date) {
  const dir = path.resolve("daily");
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const filePath = path.join(dir, `${date}.md`);
  fs.writeFileSync(filePath, content, "utf-8");

  return filePath;
}
